FROM microsoft/dotnet:2.1-sdk
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["Dendle404/Dendle404.csproj", "Dendle404/"]

RUN dotnet restore "Dendle404/Dendle404.csproj"
COPY . .
WORKDIR "/src/Dendle404"
RUN dotnet build --no-restore "Dendle404.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]